### ISSUE TITLE
[Question] Does it supports content in .md instead of .toml?

### ISSUE THREAD

**Issue by danimesq** [grego/blades#10]

**Comment by grego** [comment]
Yes it does: #8

**Comment by gagarine** [comment]
I think the example site linked in the documentation is misleading because of this.

**Comment by grego** [comment]
What is misleading there?

**Comment by gagarine** [comment]
In https://www.getblades.org/pages.html the exemple linked at the end of the page only use content in .toml. 

The code snippet in the doc only show the toml part but not a toml header in a md file. So really you have to carefully read the doc, but I think that would be unnecessary if they was a complete code snippet in md and one in toml.

**Comment by grego** [comment]
Sorry, there was a wrong link. Fixed it in https://github.com/grego/bladesite/commit/265d82202b7d08d688e4b9321ed32afc7eda3795
