### ISSUE TITLE
Table of contents with access to all of the site data

### ISSUE THREAD

**Issue by Heiss** [grego/blades#12]
In the readme, you say there is a TOC functionality. How can i use it in a theme?

Example:

In my markdown file, there are multiple headings
```markdown
# Header 1
## Subheader
# Header 2
```

Now i want something like the following html snippet to include into my templates.

```html
<ul>
<li>Header 1</li>
<li><ul>
<li>Subheader</li>
</ul></li>
<li>Header 2</li>
</ul>
```

I cannot find any examples in your provided themes for TOC.

I am playing around with the idea to create a theme, which is highly inspired by [mdBook theme](https://jorel.dev/mdBook-pagetoc/).

**Comment by grego** [comment]
ToC refers to table of contents of the site, not of the original page. This probably should be qualified in README

**Comment by Heiss** [comment]
Okay thank you. 

I implemented a new [plugin](https://github.com/Heiss/blades-heading) (i love this concept, did i said that before? :D:D:D) to use this new [Feature](https://github.com/raphlinus/pulldown-cmark/pull/522) for pulldown-cmark. You have already the right dependency (v0.9) in use for blades. So it was an easy task. Now i can use javascript to generate the page TOC in my theme.

**Comment by grego** [comment]
As all features of `pulldown_cmark` are enabled, specifying ids and classes works by default.
In fact, it is used on the [Blades site](https://github.com/grego/bladesite/blob/master/content/pages.md).
I should probably clarify this somewhere.
