### ISSUE TITLE
Netlify integration

### ISSUE THREAD

**Issue by zoosky** [grego/blades#15]
A la Zola?

**Comment by grego** [comment]
This is very well possible, however, not in my competence. You can submit an issue to Netlify to enable automatic deploys with Blades.

**Comment by zoosky** [comment]
There are different approaches. I guess if there is a large enough user base, they will add it. Before you can try to deliver your own binary, as I did in https://github.com/zoosky/blades-test

Which fails currently with
```bash
8:26:00 AM: ────────────────────────────────────────────────────────────────
8:26:00 AM:   1. Build command from Netlify app                             
8:26:00 AM: ────────────────────────────────────────────────────────────────
8:26:00 AM: ​
8:26:00 AM: $ ./bin/linux/amd64/blades all
8:26:00 AM: ./bin/linux/amd64/blades: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./bin/linux/amd64/blades)
./bin/linux/amd64/blades: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./bin/linux/amd64/blades)
./bin/linux/amd64/blades: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./bin/linux/amd64/blades)
```
Need to find out how to compile against a older version of glibc.

Now tried  release build with musl target and Netlify build command `./bin/linux/amd64-musl/blades -c ./Blades.toml all`:

```bash
​
10:30:25 AM: Post processing - HTML
10:30:24 AM: $ ./bin/linux/amd64-musl/blades -c ./Blades.toml all
10:30:24 AM: Done in 5.504ms.
```

Other approach would be using https://github.com/netlify/binrc 

This would require to invest into a Github build pipeline and publish binary artefacts as part of a release.

See Zola in https://github.com/netlify/build-image/blob/focal/included_software.md

**Comment by grego** [comment]
I added a binary release to GitHub, which should be self-contained and statically linked with MUSL.
I would be wary of using executables from GitHub, though.
