### ISSUE TITLE
Switch Template Engine

### ISSUE THREAD

**Issue by zoosky** [grego/blades#16]
For example https://github.com/mitsuhiko/minijinja possible?

**Comment by grego** [comment]
While it should be theoretically possible to support other template engines, Blades is now tightly integrated with Ramhorns.
Is there a feature you are missing?

**Comment by zoosky** [comment]
I understand, thought the plugings would ease such a change eventually.

I'd like to have Jinja2 compatible template engine, makes easier to move away from Zola and Jekyll. 

BTW, the mentioned `minijinja` is written from the origninal inventor of jinja2 python.
