### ISSUE TITLE
How to make a blog with URLs including the date?

### ISSUE THREAD

**Issue by skyfaller** [grego/blades#19]
If I wanted to use Blades to write a blog with the date in each post's URL like https://www.maximumethics.dev/blog/2020/07/my-first-post/, is this possible? Could you document how to do this? It's OK if it requires a bit more manual work than [it would with Hugo](https://gohugo.io/content-management/urls/), I understand Blades is intended to be much simpler, but I just can't figure out how to go about it, if it can be done.

The example "blogs" I see in the [theme directory](https://www.getblades.org/themes/) do not have dates in the post URLs.

Having dates in the URL would be very helpful if I were moving an existing blog from e.g. Wordpress, since [cool URIs don't change](https://www.w3.org/Provider/Style/URI.html).

**Comment by grego** [comment]
You can do this manually by setting
```toml
path = "blog/2020/07"
```
if you want a separate path for each year and month (the latest commit 837107d2a0e5977d4900236a0dd98b1b3da58796 fixes an issue with it).

Or you can set
```toml
slug = "2020-07-my-first-post"
```
to simply have the date in the URL, but not create any additional directories.
