### ISSUE TITLE
Links aren't relative

### ISSUE THREAD

**Issue by BenjaminSchool** [grego/blades#2]
When Blades generates links, it seems to generate them relative to the uri root as opposed to relatively. This causes problems because it makes it so that Blades can't be used for a subdirectory without setting the uri field, and setting the uri field makes it impossible to also view locally.

**Comment by grego** [comment]
Do you mean links generated by the templates? Those can be set up in the templates.
You could comment out the url field from the config during development.
Is there another way how you would solve it?

If you mean links generated from markdown, at the moment, they point to whatever you point them to. Changing this behaviour would require a more advanced markdown renderer.

**Comment by BenjaminSchool** [comment]
I was referring to in templates. Looking back at the templates, it does seem to be possible to change, but very difficult because of the internal url processing. I'll continue to look at it, and I might push upstream a fix on Casper.
