### ISSUE TITLE
blades build fails on output of blades init

### ISSUE THREAD

**Issue by glyn** [grego/blades#26]
I would expect building a freshly initialised directory to work, as a sanity check. Instead I got:
~~~
blades build
Error parsing config file Blades.toml: invalid type: map, expected a string at line 7 column 1
~~~

`Blades.toml` contains this:
~~~
title = "notes"
description = ""
keywords = ""
image = ""
theme = ""

[author]
name = "Glyn Normington"
~~~

It's not obvious from the [Configuration page](https://getblades.org/config.html) that there is anything incorrect.

I'm using blades v0.5.0 on Linux.

(FWIW deleting the last two lines of `Blades.toml` prevents the above error.)

**Comment by grego** [comment]
Good catch! The author field is used for some time, but the template was not updated. Fixed that in 55d24db43dfbdca36510ce54a0323c126b81fa8a.
Also fixed the documentation.

**Comment by glyn** [comment]
@grego Thanks for the speedy fix. (https://www.getblades.org/ now looks rather impoverished. I wonder if something went wrong with its theme?)

**Comment by grego** [comment]
Thanks! The stylesheet somehow got deleted, but I didn't noticed it because I had it cached, should be fixed.

**Comment by glyn** [comment]
Yeah, back to normal now. Thank you. fyi I wrote up my initial experiment [here](https://underlap.org/blades-ssg).

**Comment by grego** [comment]
Thanks. BTW, in the next version, I plan to make Blades able to generate a minimalistic site even without any templates to make the process of starting with Blades/starting a new site easier.

**Comment by glyn** [comment]
Sounds great! Thanks.

**Comment by grego** [comment]
Added a very simple theme to make a quick start painless: [42f0e71](https://github.com/grego/blades/commit/42f0e71e56d8fadf06296011e8c9355e84375186)
Will be included in the next release.
