### ISSUE TITLE
Applying Markdown to arbitrary extra fields

### ISSUE THREAD

**Issue by BenjaminSchool** [grego/blades#3]
I've looked at the documentation and the code, and it seems that it is hardcoded which fields are treated as Markdown.

I would like to be able to parse an extra field as Markdown in a template.

**Comment by grego** [comment]
Added support for markdown in strings defined in the `extra` section in 8a4d573 and release v0.1.2

**Comment by BenjaminSchool** [comment]
Thanks! That seems to add the feature I wanted. I really appreciate your quick fix, and I'd be happy to help out with tasks in the future.
