### ISSUE TITLE
Multiple slugs for a single page

### ISSUE THREAD

**Issue by BenjaminSchool** [grego/blades#5]
I would like the ability to give multiple links for a single page. I'm happy to implement this, but I see two possible approaches:

1. Make the slug variable into a collection.
2. Add a new optional variable for supplemental slugs.

Which of those would be best?

Additionally, I'd be interested in adding an option to automatically generate permalinks from file names, but that's separate and not necessarily within the scope of the main issue. Are there any plans for easy extensibility?

**Comment by grego** [comment]
Thinking about it, the option 2 should be much easier to implement (although a bit more cumbersome to use, but I think not by much), so I would go with it.
To be consistent, maybe it would be better to also add a variable for alternative paths, in case someone would like to change the whole path.

What exactly do you mean by "automatically generate permalinks from file names"?

**Comment by BenjaminSchool** [comment]
Are you saying to only add a variable for alternate paths and not one for alternate slugs? That would seem like a logical solution to me; if you're proposing to add both, it would be a bit complicated to work out all of the possible permutations. Once you clarify this, I'll write a pull request to implement it.

I meant some functionality to give every content source file an output based off of its filename in addition to whatever other output files were produced.

**Comment by grego** [comment]
I believe having just one variable for alternate paths is sufficient.

By default, the slug is based on the filename. So if you leave the `slug` variable empty and inhabit the new `alternative_paths` (ideas for a shorter name welcome) variable, I think you should get the desired behaviour.

**Comment by grego** [comment]
Added the `alternative_paths` variable in 008193f673ce7f19866c6906a5679e297b9e9162.
